# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xsulca00/repos/IFJ

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xsulca00/repos/IFJ

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xsulca00/repos/IFJ/CMakeFiles /home/xsulca00/repos/IFJ/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xsulca00/repos/IFJ/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named interpret-expr-test

# Build rule for target.
interpret-expr-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interpret-expr-test
.PHONY : interpret-expr-test

# fast build rule for target.
interpret-expr-test/fast:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/build
.PHONY : interpret-expr-test/fast

#=============================================================================
# Target rules for targets named interpret-str-test

# Build rule for target.
interpret-str-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interpret-str-test
.PHONY : interpret-str-test

# fast build rule for target.
interpret-str-test/fast:
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/build
.PHONY : interpret-str-test/fast

#=============================================================================
# Target rules for targets named interpret_idea

# Build rule for target.
interpret_idea: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interpret_idea
.PHONY : interpret_idea

# fast build rule for target.
interpret_idea/fast:
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/build
.PHONY : interpret_idea/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named my_scanner

# Build rule for target.
my_scanner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_scanner
.PHONY : my_scanner

# fast build rule for target.
my_scanner/fast:
	$(MAKE) -f CMakeFiles/my_scanner.dir/build.make CMakeFiles/my_scanner.dir/build
.PHONY : my_scanner/fast

#=============================================================================
# Target rules for targets named op_parser

# Build rule for target.
op_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 op_parser
.PHONY : op_parser

# fast build rule for target.
op_parser/fast:
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/build
.PHONY : op_parser/fast

#=============================================================================
# Target rules for targets named scanner

# Build rule for target.
scanner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scanner
.PHONY : scanner

# fast build rule for target.
scanner/fast:
	$(MAKE) -f CMakeFiles/scanner.dir/build.make CMakeFiles/scanner.dir/build
.PHONY : scanner/fast

#=============================================================================
# Target rules for targets named stable-test

# Build rule for target.
stable-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stable-test
.PHONY : stable-test

# fast build rule for target.
stable-test/fast:
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/build
.PHONY : stable-test/fast

#=============================================================================
# Target rules for targets named str_test

# Build rule for target.
str_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 str_test
.PHONY : str_test

# fast build rule for target.
str_test/fast:
	$(MAKE) -f CMakeFiles/str_test.dir/build.make CMakeFiles/str_test.dir/build
.PHONY : str_test/fast

ial.o: ial.c.o

.PHONY : ial.o

# target to build an object file
ial.c.o:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/ial.c.o
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/ial.c.o
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/ial.c.o
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/ial.c.o
	$(MAKE) -f CMakeFiles/str_test.dir/build.make CMakeFiles/str_test.dir/ial.c.o
.PHONY : ial.c.o

ial.i: ial.c.i

.PHONY : ial.i

# target to preprocess a source file
ial.c.i:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/ial.c.i
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/ial.c.i
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/ial.c.i
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/ial.c.i
	$(MAKE) -f CMakeFiles/str_test.dir/build.make CMakeFiles/str_test.dir/ial.c.i
.PHONY : ial.c.i

ial.s: ial.c.s

.PHONY : ial.s

# target to generate assembly for a file
ial.c.s:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/ial.c.s
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/ial.c.s
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/ial.c.s
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/ial.c.s
	$(MAKE) -f CMakeFiles/str_test.dir/build.make CMakeFiles/str_test.dir/ial.c.s
.PHONY : ial.c.s

instruction_list.o: instruction_list.c.o

.PHONY : instruction_list.o

# target to build an object file
instruction_list.c.o:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/instruction_list.c.o
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/instruction_list.c.o
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/instruction_list.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/instruction_list.c.o
.PHONY : instruction_list.c.o

instruction_list.i: instruction_list.c.i

.PHONY : instruction_list.i

# target to preprocess a source file
instruction_list.c.i:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/instruction_list.c.i
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/instruction_list.c.i
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/instruction_list.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/instruction_list.c.i
.PHONY : instruction_list.c.i

instruction_list.s: instruction_list.c.s

.PHONY : instruction_list.s

# target to generate assembly for a file
instruction_list.c.s:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/instruction_list.c.s
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/instruction_list.c.s
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/instruction_list.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/instruction_list.c.s
.PHONY : instruction_list.c.s

interpret-expr-test.o: interpret-expr-test.c.o

.PHONY : interpret-expr-test.o

# target to build an object file
interpret-expr-test.c.o:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/interpret-expr-test.c.o
.PHONY : interpret-expr-test.c.o

interpret-expr-test.i: interpret-expr-test.c.i

.PHONY : interpret-expr-test.i

# target to preprocess a source file
interpret-expr-test.c.i:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/interpret-expr-test.c.i
.PHONY : interpret-expr-test.c.i

interpret-expr-test.s: interpret-expr-test.c.s

.PHONY : interpret-expr-test.s

# target to generate assembly for a file
interpret-expr-test.c.s:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/interpret-expr-test.c.s
.PHONY : interpret-expr-test.c.s

interpret-str-test.o: interpret-str-test.c.o

.PHONY : interpret-str-test.o

# target to build an object file
interpret-str-test.c.o:
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/interpret-str-test.c.o
.PHONY : interpret-str-test.c.o

interpret-str-test.i: interpret-str-test.c.i

.PHONY : interpret-str-test.i

# target to preprocess a source file
interpret-str-test.c.i:
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/interpret-str-test.c.i
.PHONY : interpret-str-test.c.i

interpret-str-test.s: interpret-str-test.c.s

.PHONY : interpret-str-test.s

# target to generate assembly for a file
interpret-str-test.c.s:
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/interpret-str-test.c.s
.PHONY : interpret-str-test.c.s

interpret.o: interpret.c.o

.PHONY : interpret.o

# target to build an object file
interpret.c.o:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/interpret.c.o
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/interpret.c.o
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/interpret.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/interpret.c.o
.PHONY : interpret.c.o

interpret.i: interpret.c.i

.PHONY : interpret.i

# target to preprocess a source file
interpret.c.i:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/interpret.c.i
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/interpret.c.i
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/interpret.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/interpret.c.i
.PHONY : interpret.c.i

interpret.s: interpret.c.s

.PHONY : interpret.s

# target to generate assembly for a file
interpret.c.s:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/interpret.c.s
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/interpret.c.s
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/interpret.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/interpret.c.s
.PHONY : interpret.c.s

op_prec_parser/op-parser.o: op_prec_parser/op-parser.c.o

.PHONY : op_prec_parser/op-parser.o

# target to build an object file
op_prec_parser/op-parser.c.o:
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/op_prec_parser/op-parser.c.o
.PHONY : op_prec_parser/op-parser.c.o

op_prec_parser/op-parser.i: op_prec_parser/op-parser.c.i

.PHONY : op_prec_parser/op-parser.i

# target to preprocess a source file
op_prec_parser/op-parser.c.i:
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/op_prec_parser/op-parser.c.i
.PHONY : op_prec_parser/op-parser.c.i

op_prec_parser/op-parser.s: op_prec_parser/op-parser.c.s

.PHONY : op_prec_parser/op-parser.s

# target to generate assembly for a file
op_prec_parser/op-parser.c.s:
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/op_prec_parser/op-parser.c.s
.PHONY : op_prec_parser/op-parser.c.s

op_prec_parser/utils/dynamic_stack.o: op_prec_parser/utils/dynamic_stack.c.o

.PHONY : op_prec_parser/utils/dynamic_stack.o

# target to build an object file
op_prec_parser/utils/dynamic_stack.c.o:
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/op_prec_parser/utils/dynamic_stack.c.o
.PHONY : op_prec_parser/utils/dynamic_stack.c.o

op_prec_parser/utils/dynamic_stack.i: op_prec_parser/utils/dynamic_stack.c.i

.PHONY : op_prec_parser/utils/dynamic_stack.i

# target to preprocess a source file
op_prec_parser/utils/dynamic_stack.c.i:
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/op_prec_parser/utils/dynamic_stack.c.i
.PHONY : op_prec_parser/utils/dynamic_stack.c.i

op_prec_parser/utils/dynamic_stack.s: op_prec_parser/utils/dynamic_stack.c.s

.PHONY : op_prec_parser/utils/dynamic_stack.s

# target to generate assembly for a file
op_prec_parser/utils/dynamic_stack.c.s:
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/op_prec_parser/utils/dynamic_stack.c.s
.PHONY : op_prec_parser/utils/dynamic_stack.c.s

scanner-unit.o: scanner-unit.c.o

.PHONY : scanner-unit.o

# target to build an object file
scanner-unit.c.o:
	$(MAKE) -f CMakeFiles/scanner.dir/build.make CMakeFiles/scanner.dir/scanner-unit.c.o
.PHONY : scanner-unit.c.o

scanner-unit.i: scanner-unit.c.i

.PHONY : scanner-unit.i

# target to preprocess a source file
scanner-unit.c.i:
	$(MAKE) -f CMakeFiles/scanner.dir/build.make CMakeFiles/scanner.dir/scanner-unit.c.i
.PHONY : scanner-unit.c.i

scanner-unit.s: scanner-unit.c.s

.PHONY : scanner-unit.s

# target to generate assembly for a file
scanner-unit.c.s:
	$(MAKE) -f CMakeFiles/scanner.dir/build.make CMakeFiles/scanner.dir/scanner-unit.c.s
.PHONY : scanner-unit.c.s

scanner-unit_alt.o: scanner-unit_alt.c.o

.PHONY : scanner-unit_alt.o

# target to build an object file
scanner-unit_alt.c.o:
	$(MAKE) -f CMakeFiles/my_scanner.dir/build.make CMakeFiles/my_scanner.dir/scanner-unit_alt.c.o
.PHONY : scanner-unit_alt.c.o

scanner-unit_alt.i: scanner-unit_alt.c.i

.PHONY : scanner-unit_alt.i

# target to preprocess a source file
scanner-unit_alt.c.i:
	$(MAKE) -f CMakeFiles/my_scanner.dir/build.make CMakeFiles/my_scanner.dir/scanner-unit_alt.c.i
.PHONY : scanner-unit_alt.c.i

scanner-unit_alt.s: scanner-unit_alt.c.s

.PHONY : scanner-unit_alt.s

# target to generate assembly for a file
scanner-unit_alt.c.s:
	$(MAKE) -f CMakeFiles/my_scanner.dir/build.make CMakeFiles/my_scanner.dir/scanner-unit_alt.c.s
.PHONY : scanner-unit_alt.c.s

scanner.o: scanner.c.o

.PHONY : scanner.o

# target to build an object file
scanner.c.o:
	$(MAKE) -f CMakeFiles/scanner.dir/build.make CMakeFiles/scanner.dir/scanner.c.o
.PHONY : scanner.c.o

scanner.i: scanner.c.i

.PHONY : scanner.i

# target to preprocess a source file
scanner.c.i:
	$(MAKE) -f CMakeFiles/scanner.dir/build.make CMakeFiles/scanner.dir/scanner.c.i
.PHONY : scanner.c.i

scanner.s: scanner.c.s

.PHONY : scanner.s

# target to generate assembly for a file
scanner.c.s:
	$(MAKE) -f CMakeFiles/scanner.dir/build.make CMakeFiles/scanner.dir/scanner.c.s
.PHONY : scanner.c.s

scanner_alt.o: scanner_alt.c.o

.PHONY : scanner_alt.o

# target to build an object file
scanner_alt.c.o:
	$(MAKE) -f CMakeFiles/my_scanner.dir/build.make CMakeFiles/my_scanner.dir/scanner_alt.c.o
.PHONY : scanner_alt.c.o

scanner_alt.i: scanner_alt.c.i

.PHONY : scanner_alt.i

# target to preprocess a source file
scanner_alt.c.i:
	$(MAKE) -f CMakeFiles/my_scanner.dir/build.make CMakeFiles/my_scanner.dir/scanner_alt.c.i
.PHONY : scanner_alt.c.i

scanner_alt.s: scanner_alt.c.s

.PHONY : scanner_alt.s

# target to generate assembly for a file
scanner_alt.c.s:
	$(MAKE) -f CMakeFiles/my_scanner.dir/build.make CMakeFiles/my_scanner.dir/scanner_alt.c.s
.PHONY : scanner_alt.c.s

stable-test.o: stable-test.c.o

.PHONY : stable-test.o

# target to build an object file
stable-test.c.o:
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/stable-test.c.o
.PHONY : stable-test.c.o

stable-test.i: stable-test.c.i

.PHONY : stable-test.i

# target to preprocess a source file
stable-test.c.i:
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/stable-test.c.i
.PHONY : stable-test.c.i

stable-test.s: stable-test.c.s

.PHONY : stable-test.s

# target to generate assembly for a file
stable-test.c.s:
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/stable-test.c.s
.PHONY : stable-test.c.s

stable.o: stable.c.o

.PHONY : stable.o

# target to build an object file
stable.c.o:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/stable.c.o
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/stable.c.o
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/stable.c.o
.PHONY : stable.c.o

stable.i: stable.c.i

.PHONY : stable.i

# target to preprocess a source file
stable.c.i:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/stable.c.i
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/stable.c.i
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/stable.c.i
.PHONY : stable.c.i

stable.s: stable.c.s

.PHONY : stable.s

# target to generate assembly for a file
stable.c.s:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/stable.c.s
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/stable.c.s
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/stable.c.s
.PHONY : stable.c.s

stack.o: stack.c.o

.PHONY : stack.o

# target to build an object file
stack.c.o:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/stack.c.o
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/stack.c.o
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/stack.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stack.c.o
.PHONY : stack.c.o

stack.i: stack.c.i

.PHONY : stack.i

# target to preprocess a source file
stack.c.i:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/stack.c.i
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/stack.c.i
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/stack.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stack.c.i
.PHONY : stack.c.i

stack.s: stack.c.s

.PHONY : stack.s

# target to generate assembly for a file
stack.c.s:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/stack.c.s
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/stack.c.s
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/stack.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stack.c.s
.PHONY : stack.c.s

str.o: str.c.o

.PHONY : str.o

# target to build an object file
str.c.o:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/str.c.o
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/str.c.o
	$(MAKE) -f CMakeFiles/my_scanner.dir/build.make CMakeFiles/my_scanner.dir/str.c.o
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/str.c.o
	$(MAKE) -f CMakeFiles/scanner.dir/build.make CMakeFiles/scanner.dir/str.c.o
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/str.c.o
	$(MAKE) -f CMakeFiles/str_test.dir/build.make CMakeFiles/str_test.dir/str.c.o
.PHONY : str.c.o

str.i: str.c.i

.PHONY : str.i

# target to preprocess a source file
str.c.i:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/str.c.i
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/str.c.i
	$(MAKE) -f CMakeFiles/my_scanner.dir/build.make CMakeFiles/my_scanner.dir/str.c.i
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/str.c.i
	$(MAKE) -f CMakeFiles/scanner.dir/build.make CMakeFiles/scanner.dir/str.c.i
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/str.c.i
	$(MAKE) -f CMakeFiles/str_test.dir/build.make CMakeFiles/str_test.dir/str.c.i
.PHONY : str.c.i

str.s: str.c.s

.PHONY : str.s

# target to generate assembly for a file
str.c.s:
	$(MAKE) -f CMakeFiles/interpret-expr-test.dir/build.make CMakeFiles/interpret-expr-test.dir/str.c.s
	$(MAKE) -f CMakeFiles/interpret-str-test.dir/build.make CMakeFiles/interpret-str-test.dir/str.c.s
	$(MAKE) -f CMakeFiles/my_scanner.dir/build.make CMakeFiles/my_scanner.dir/str.c.s
	$(MAKE) -f CMakeFiles/op_parser.dir/build.make CMakeFiles/op_parser.dir/str.c.s
	$(MAKE) -f CMakeFiles/scanner.dir/build.make CMakeFiles/scanner.dir/str.c.s
	$(MAKE) -f CMakeFiles/stable-test.dir/build.make CMakeFiles/stable-test.dir/str.c.s
	$(MAKE) -f CMakeFiles/str_test.dir/build.make CMakeFiles/str_test.dir/str.c.s
.PHONY : str.c.s

str_test.o: str_test.c.o

.PHONY : str_test.o

# target to build an object file
str_test.c.o:
	$(MAKE) -f CMakeFiles/str_test.dir/build.make CMakeFiles/str_test.dir/str_test.c.o
.PHONY : str_test.c.o

str_test.i: str_test.c.i

.PHONY : str_test.i

# target to preprocess a source file
str_test.c.i:
	$(MAKE) -f CMakeFiles/str_test.dir/build.make CMakeFiles/str_test.dir/str_test.c.i
.PHONY : str_test.c.i

str_test.s: str_test.c.s

.PHONY : str_test.s

# target to generate assembly for a file
str_test.c.s:
	$(MAKE) -f CMakeFiles/str_test.dir/build.make CMakeFiles/str_test.dir/str_test.c.s
.PHONY : str_test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... str_test"
	@echo "... interpret_idea"
	@echo "... main"
	@echo "... interpret-str-test"
	@echo "... op_parser"
	@echo "... my_scanner"
	@echo "... stable-test"
	@echo "... scanner"
	@echo "... interpret-expr-test"
	@echo "... rebuild_cache"
	@echo "... ial.o"
	@echo "... ial.i"
	@echo "... ial.s"
	@echo "... instruction_list.o"
	@echo "... instruction_list.i"
	@echo "... instruction_list.s"
	@echo "... interpret-expr-test.o"
	@echo "... interpret-expr-test.i"
	@echo "... interpret-expr-test.s"
	@echo "... interpret-str-test.o"
	@echo "... interpret-str-test.i"
	@echo "... interpret-str-test.s"
	@echo "... interpret.o"
	@echo "... interpret.i"
	@echo "... interpret.s"
	@echo "... op_prec_parser/op-parser.o"
	@echo "... op_prec_parser/op-parser.i"
	@echo "... op_prec_parser/op-parser.s"
	@echo "... op_prec_parser/utils/dynamic_stack.o"
	@echo "... op_prec_parser/utils/dynamic_stack.i"
	@echo "... op_prec_parser/utils/dynamic_stack.s"
	@echo "... scanner-unit.o"
	@echo "... scanner-unit.i"
	@echo "... scanner-unit.s"
	@echo "... scanner-unit_alt.o"
	@echo "... scanner-unit_alt.i"
	@echo "... scanner-unit_alt.s"
	@echo "... scanner.o"
	@echo "... scanner.i"
	@echo "... scanner.s"
	@echo "... scanner_alt.o"
	@echo "... scanner_alt.i"
	@echo "... scanner_alt.s"
	@echo "... stable-test.o"
	@echo "... stable-test.i"
	@echo "... stable-test.s"
	@echo "... stable.o"
	@echo "... stable.i"
	@echo "... stable.s"
	@echo "... stack.o"
	@echo "... stack.i"
	@echo "... stack.s"
	@echo "... str.o"
	@echo "... str.i"
	@echo "... str.s"
	@echo "... str_test.o"
	@echo "... str_test.i"
	@echo "... str_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

