# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adio/ClionProjects/IFJ

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adio/ClionProjects/IFJ

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adio/ClionProjects/IFJ/CMakeFiles /home/adio/ClionProjects/IFJ/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adio/ClionProjects/IFJ/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named inter_idea_recursion

# Build rule for target.
inter_idea_recursion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 inter_idea_recursion
.PHONY : inter_idea_recursion

# fast build rule for target.
inter_idea_recursion/fast:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/build
.PHONY : inter_idea_recursion/fast

#=============================================================================
# Target rules for targets named interpret_idea

# Build rule for target.
interpret_idea: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interpret_idea
.PHONY : interpret_idea

# fast build rule for target.
interpret_idea/fast:
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/build
.PHONY : interpret_idea/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

instruction_list.o: instruction_list.c.o
.PHONY : instruction_list.o

# target to build an object file
instruction_list.c.o:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/instruction_list.c.o
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/instruction_list.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/instruction_list.c.o
.PHONY : instruction_list.c.o

instruction_list.i: instruction_list.c.i
.PHONY : instruction_list.i

# target to preprocess a source file
instruction_list.c.i:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/instruction_list.c.i
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/instruction_list.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/instruction_list.c.i
.PHONY : instruction_list.c.i

instruction_list.s: instruction_list.c.s
.PHONY : instruction_list.s

# target to generate assembly for a file
instruction_list.c.s:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/instruction_list.c.s
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/instruction_list.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/instruction_list.c.s
.PHONY : instruction_list.c.s

inter_idea_recursion.o: inter_idea_recursion.c.o
.PHONY : inter_idea_recursion.o

# target to build an object file
inter_idea_recursion.c.o:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/inter_idea_recursion.c.o
.PHONY : inter_idea_recursion.c.o

inter_idea_recursion.i: inter_idea_recursion.c.i
.PHONY : inter_idea_recursion.i

# target to preprocess a source file
inter_idea_recursion.c.i:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/inter_idea_recursion.c.i
.PHONY : inter_idea_recursion.c.i

inter_idea_recursion.s: inter_idea_recursion.c.s
.PHONY : inter_idea_recursion.s

# target to generate assembly for a file
inter_idea_recursion.c.s:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/inter_idea_recursion.c.s
.PHONY : inter_idea_recursion.c.s

interpret.o: interpret.c.o
.PHONY : interpret.o

# target to build an object file
interpret.c.o:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/interpret.c.o
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/interpret.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/interpret.c.o
.PHONY : interpret.c.o

interpret.i: interpret.c.i
.PHONY : interpret.i

# target to preprocess a source file
interpret.c.i:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/interpret.c.i
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/interpret.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/interpret.c.i
.PHONY : interpret.c.i

interpret.s: interpret.c.s
.PHONY : interpret.s

# target to generate assembly for a file
interpret.c.s:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/interpret.c.s
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/interpret.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/interpret.c.s
.PHONY : interpret.c.s

interpret_idea.o: interpret_idea.c.o
.PHONY : interpret_idea.o

# target to build an object file
interpret_idea.c.o:
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/interpret_idea.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/interpret_idea.c.o
.PHONY : interpret_idea.c.o

interpret_idea.i: interpret_idea.c.i
.PHONY : interpret_idea.i

# target to preprocess a source file
interpret_idea.c.i:
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/interpret_idea.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/interpret_idea.c.i
.PHONY : interpret_idea.c.i

interpret_idea.s: interpret_idea.c.s
.PHONY : interpret_idea.s

# target to generate assembly for a file
interpret_idea.c.s:
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/interpret_idea.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/interpret_idea.c.s
.PHONY : interpret_idea.c.s

stable.o: stable.c.o
.PHONY : stable.o

# target to build an object file
stable.c.o:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/stable.c.o
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/stable.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stable.c.o
.PHONY : stable.c.o

stable.i: stable.c.i
.PHONY : stable.i

# target to preprocess a source file
stable.c.i:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/stable.c.i
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/stable.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stable.c.i
.PHONY : stable.c.i

stable.s: stable.c.s
.PHONY : stable.s

# target to generate assembly for a file
stable.c.s:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/stable.c.s
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/stable.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stable.c.s
.PHONY : stable.c.s

stack.o: stack.c.o
.PHONY : stack.o

# target to build an object file
stack.c.o:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/stack.c.o
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/stack.c.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stack.c.o
.PHONY : stack.c.o

stack.i: stack.c.i
.PHONY : stack.i

# target to preprocess a source file
stack.c.i:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/stack.c.i
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/stack.c.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stack.c.i
.PHONY : stack.c.i

stack.s: stack.c.s
.PHONY : stack.s

# target to generate assembly for a file
stack.c.s:
	$(MAKE) -f CMakeFiles/inter_idea_recursion.dir/build.make CMakeFiles/inter_idea_recursion.dir/stack.c.s
	$(MAKE) -f CMakeFiles/interpret_idea.dir/build.make CMakeFiles/interpret_idea.dir/stack.c.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/stack.c.s
.PHONY : stack.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... inter_idea_recursion"
	@echo "... interpret_idea"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... instruction_list.o"
	@echo "... instruction_list.i"
	@echo "... instruction_list.s"
	@echo "... inter_idea_recursion.o"
	@echo "... inter_idea_recursion.i"
	@echo "... inter_idea_recursion.s"
	@echo "... interpret.o"
	@echo "... interpret.i"
	@echo "... interpret.s"
	@echo "... interpret_idea.o"
	@echo "... interpret_idea.i"
	@echo "... interpret_idea.s"
	@echo "... stable.o"
	@echo "... stable.i"
	@echo "... stable.s"
	@echo "... stack.o"
	@echo "... stack.i"
	@echo "... stack.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

